services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /home/pavel/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  chrony:
    image: publicarray/chrony:latest
    container_name: Chrony
    restart: unless-stopped
    ports:
    - 123:123/udp
    volumes:
    - ./chrony/chrony.conf:/etc/chrony.conf
    cap_add:
      - SYS_TIME
    network_mode: bridge
